"""empty message

Revision ID: 8b0e3c53ffa1
Revises: 
Create Date: 2023-12-05 14:30:58.875287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0e3c53ffa1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('artist', sa.String(length=50), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_albums_artist'), ['artist'], unique=False)
        batch_op.create_index(batch_op.f('ix_albums_genre'), ['genre'], unique=False)
        batch_op.create_index(batch_op.f('ix_albums_title'), ['title'], unique=False)

    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('artist', sa.String(length=50), nullable=True),
    sa.Column('review', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('album', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_album'), ['album'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_artist'), ['artist'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_rating'), ['rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_review'), ['review'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_username'), ['username'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('profile_photo', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_password'), ['password'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profile_photo'), ['profile_photo'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_profile_photo'))
        batch_op.drop_index(batch_op.f('ix_user_password'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_username'))
        batch_op.drop_index(batch_op.f('ix_review_title'))
        batch_op.drop_index(batch_op.f('ix_review_review'))
        batch_op.drop_index(batch_op.f('ix_review_rating'))
        batch_op.drop_index(batch_op.f('ix_review_artist'))
        batch_op.drop_index(batch_op.f('ix_review_album'))

    op.drop_table('review')
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_albums_title'))
        batch_op.drop_index(batch_op.f('ix_albums_genre'))
        batch_op.drop_index(batch_op.f('ix_albums_artist'))

    op.drop_table('albums')
    # ### end Alembic commands ###
